# Based off of https://github.com/minimaxir/gpt-2-cloud-run/blob/master/Dockerfile
FROM arm32v6/python:3.8-alpine

RUN apk update && apk add gcc musl-dev py3-opencv zlib-dev jpeg-dev

WORKDIR /code

ENV PYTHONPATH=$PYTHONPATH:/usr/lib/python3.10/site-packages

RUN pip3 --no-cache-dir install -U py-cord python-dotenv markovchain pillow

COPY .env src/ secret-scholars-bot-config.json ./

RUN printf "build_time=%s" "'`date -Iseconds`'" > autogen_buildtime.py

# CMD [ "python", "./bot.py" ]
